name: "Accion saludo"
description: "Saludar a alguien"
author: "rcamps@fibertel.com.ar"

inputs:
  MY_NAME:
    description: "A quien saludar"
    required: true
    default: "Todos"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
