name: Un saludo de mi parte
on: 
    workflow_dispatch:
    push:
jobs:
  build:
    name: Saludo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Rodrigo Camps Palacios Malarino"
