name: Un saludo de mi parte
on: 
    workflow_dispatch:
      inputs:
        nombre:
          type: choice
          description: a quien saludar
          options:
          - Abel
          - Rodrigo
          - Gustavo
       message:
         required: true
       environment:
         type: environment
    push:
jobs:
  saludar:
    name: Saludo2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Mandar saludo
        run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", ""]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"
        with:
          MY_NAME: "Rodrigo Camps Palacios Malarino"
