name: Un saludo desde bash 
run-name: Saludo desde bash
on: 
  workflow_dispatch:
    inputs:
      nombre:
        type: choice
        description: a quien saludar
        options:
        - Abel
        - Rodrigo
        - Gustavo
      mensaje:
        required: true
      environment:
        type: environment
jobs:
  saludar:
    name: Saludo2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Mandar saludo
        run: echo "Mensaje para ${{ github.event.inputs.nombre }} ${{ github.event.inputs.mensaje }} Entorno: ${{ vars.mensajito }}"
